// Code generated by generate-maintenance-handler. DO NOT EDIT.
/* eslint-disable */
import EventsHandler from 'api/eventsHandler'
import MaintenancesStore from 'db/maintenances'
import MaintenanceUpdatesStore from 'db/maintenanceUpdates'

export async function handle (event, context, callback) {
  try {
    const handler = new EventsHandler(new MaintenancesStore(), new MaintenanceUpdatesStore())
    const maintenances = await handler.listEvents()
    callback(null, maintenances.map(maintenance => maintenance.objectify()))
  } catch (error) {
    console.log(error.message)
    console.log(error.stack)
    callback('Error: failed to get maintenances list')
  }
}
