// Code generated by generate-maintenance-handler. DO NOT EDIT.
/* eslint-disable */
import EventsHandler from 'api/eventsHandler'
import { messageType } from 'aws/sns'
import MaintenancesStore from 'db/maintenances'
import MaintenanceUpdatesStore from 'db/maintenanceUpdates'

export async function handle (event, context, callback) {
  try {
    const handler = new EventsHandler(new MaintenancesStore(), new MaintenanceUpdatesStore())
    const maintenanceID = event.params.maintenanceid
    await handler.deleteEvent(maintenanceID, messageType.maintenanceDeleted)
  } catch (error) {
    console.log(error.message)
    console.log(error.stack)
    callback('Error: failed to delete the maintenance')
  }
}
