// Code generated by generate-maintenance-handler. DO NOT EDIT.
/* eslint-disable */
import EventsHandler from 'api/eventsHandler'
import MaintenancesStore from 'db/maintenances'
import MaintenanceUpdatesStore from 'db/maintenanceUpdates'
import { NotFoundError } from 'utils/errors'

export async function handle (event, context, callback) {
  try {
    const maintenanceID = event.params.maintenanceid
    const handler = new EventsHandler(new MaintenancesStore(), new MaintenanceUpdatesStore())
    let [maintenance, maintenanceUpdates] = await handler.getEvent(maintenanceID)

    // Show the maintenances as if will happen tomorrow.
    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    const tomorrowDate = tomorrow.toISOString().replace(/T[0-9:.]+Z$/, '')
    maintenance.createdAt = tomorrowDate + maintenance.createdAt.replace(/^[0-9-]+/, '')
    maintenance.updatedAt = tomorrowDate + maintenance.updatedAt.replace(/^[0-9-]+/, '')
    maintenance.startAt = tomorrowDate + maintenance.startAt.replace(/^[0-9-]+/, '')
    maintenance.endAt = tomorrowDate + maintenance.endAt.replace(/^[0-9-]+/, '')

    const yesterday = new Date()
    yesterday.setDate(yesterday.getDate() - 1)
    const yesterdayDate = yesterday.toISOString().replace(/T[0-9:.]+Z$/, '')
    // Show the maintenance updates as if they have happened yesterday.
    maintenanceUpdates = maintenanceUpdates.map(maintenanceUpdate => {
      maintenanceUpdate.createdAt = yesterdayDate + maintenanceUpdate.createdAt.replace(/^[0-9-]+/, '')
      maintenanceUpdate.updatedAt = yesterdayDate + maintenanceUpdate.updatedAt.replace(/^[0-9-]+/, '')
      return maintenanceUpdate
    })

    callback(null, {...maintenance.objectify(), maintenanceUpdates: maintenanceUpdates.map(upd => upd.objectify())})
  } catch (error) {
    console.log(error.message)
    console.log(error.stack)
    switch (error.name) {
      case NotFoundError.name:
        callback('Error: an item not found')
        break
      default:
        callback('Error: failed to get an maintenance')
    }
  }
}
